### PR TITLE
Create docker environment and Codespace for easy onborading 

### PR DESCRIPTION
**Pull request by erlichsefi**
Define three levels of the docker environment, base, dev, and test.
base - to run the code and selenium in docker. 
dev - to allow remote code development/execution.
test - to run the testing in the same exact environment.

### CODE REVIEW

**Comment by erlichsefi** [comment]
Hi @richardyc @BaseInfinity WDYT?

**Comment by richardyc** [comment]
thanks! taking a look now

**Review by richardyc — APPROVED** [review]
LGTM, thanks for the contribution!

**Comment by BaseInfinity** [comment]
Sorry I'm late to the party, this is awesome!

**Pull request merged**
